//we can also handle multiple exceptions using a single catch 

public class ExceptionDemo 
{
	public static void main(String[] args)
	{
		try
		{
			int a[] = new int[5];
			a[4] = 8;
			int i = 7;
			int j = 0;
			int k=i/j;
			System.out.println("output is " + k);
			System.out.println("Bye");
		}
		catch(ArithmeticException | ArrayIndexOutOfBoundsException e)
		{
		
			System.out.println("Error");
		}
		
		
	}
}
